/* The following code was generated by JFlex 1.4.3 on 25/08/12 13:05 */

package com.github.kumaraman21.intellijbehave.highlighter;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.Stack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 25/08/12 13:05 from the specification file
 * <tt>Story.flex</tt>
 */
class _StoryLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int IN_SCENARIO = 6;
  public static final int IN_STORY = 4;
  public static final int YYINITIAL = 0;
  public static final int IN_TABLE = 12;
  public static final int IN_DIRECTIVE = 2;
  public static final int IN_STEP = 8;
  public static final int IN_META = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\16\1\27\13\0"+
    "\1\30\14\0\1\15\5\0\1\31\1\25\5\0\1\21\5\0\1\17"+
    "\5\0\1\5\1\23\2\0\1\23\11\0\1\11\1\0\1\6\1\26"+
    "\1\7\2\0\1\24\1\13\4\0\1\10\1\14\2\0\1\12\1\0"+
    "\1\20\1\0\1\22\5\0\1\4\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\2\2\7\1\1\3\1\4\1\5\6\3"+
    "\2\4\1\6\1\7\1\10\1\11\1\12\2\13\1\14"+
    "\1\15\6\1\6\0\1\15\6\0\4\1\4\0\1\16"+
    "\6\0\2\1\2\0\1\17\4\0\1\1\1\0\1\20"+
    "\2\0\1\1\2\0\1\1\2\0\1\1\4\0\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\32\0\64\0\116\0\150\0\202\0\234\0\266"+
    "\0\320\0\352\0\u0104\0\u011e\0\u0138\0\u0152\0\u016c\0\u0186"+
    "\0\u01a0\0\352\0\u01ba\0\352\0\u01d4\0\u01ee\0\u0208\0\u0222"+
    "\0\u023c\0\u0256\0\u0270\0\u028a\0\u02a4\0\u02be\0\u02d8\0\u02f2"+
    "\0\u030c\0\u0326\0\352\0\352\0\u0104\0\u0340\0\u035a\0\u0374"+
    "\0\u038e\0\u03a8\0\u03c2\0\u03dc\0\u03f6\0\u0410\0\u042a\0\u0444"+
    "\0\u045e\0\352\0\u0478\0\u0492\0\u04ac\0\u04c6\0\u04e0\0\u04fa"+
    "\0\u0514\0\u052e\0\u0548\0\u0562\0\u057c\0\u0596\0\u05b0\0\u05ca"+
    "\0\u05e4\0\u05fe\0\u0618\0\u0632\0\u064c\0\u0666\0\u0680\0\u069a"+
    "\0\u06b4\0\u06ce\0\u06e8\0\352\0\u0702\0\u071c\0\u0736\0\u0750"+
    "\0\u076a\0\u0784\0\352\0\u079e\0\u07b8\0\u07d2\0\u07ec\0\u0806"+
    "\0\u0820\0\u083a\0\u0854\0\u086e\0\u0888\0\u08a2\0\u08bc\0\u08d6"+
    "\0\352";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\10\1\13\1\14\11\10\1\15"+
    "\1\10\1\16\1\10\1\17\1\10\1\20\1\10\1\21"+
    "\2\10\1\22\3\23\1\24\1\25\10\22\1\23\1\26"+
    "\1\22\1\27\1\22\1\30\1\22\1\31\1\22\1\32"+
    "\2\22\1\10\1\33\1\34\27\10\1\35\1\33\1\34"+
    "\27\35\1\36\1\33\1\34\27\36\1\37\1\33\1\34"+
    "\26\37\1\40\1\41\1\42\1\43\1\41\1\44\25\41"+
    "\1\10\2\0\27\10\2\0\1\12\61\0\1\45\2\0"+
    "\27\45\1\10\2\0\3\10\1\46\24\10\2\0\4\10"+
    "\1\47\23\10\2\0\10\10\1\50\17\10\2\0\21\10"+
    "\1\51\6\10\2\0\5\10\1\52\22\10\2\0\25\10"+
    "\1\53\1\10\1\0\3\23\12\0\1\23\21\0\1\54"+
    "\32\0\1\55\35\0\1\56\42\0\1\57\15\0\1\60"+
    "\51\0\1\61\3\0\1\34\1\0\1\62\1\63\11\0"+
    "\1\64\1\0\1\65\1\0\1\66\1\0\1\67\1\0"+
    "\1\70\6\0\1\62\1\63\11\0\1\64\1\0\1\65"+
    "\1\0\1\66\1\0\1\67\1\0\1\70\2\0\1\35"+
    "\2\0\27\35\1\36\2\0\27\36\1\37\2\0\27\37"+
    "\1\40\2\0\1\37\12\40\1\37\13\40\1\41\2\0"+
    "\1\41\1\0\25\41\2\0\1\43\27\0\1\10\2\0"+
    "\4\10\1\71\23\10\2\0\15\10\1\72\12\10\2\0"+
    "\17\10\1\51\10\10\2\0\4\10\1\73\23\10\2\0"+
    "\23\10\1\74\4\10\2\0\25\10\1\13\1\10\7\0"+
    "\1\75\42\0\1\76\33\0\1\57\16\0\1\77\50\0"+
    "\1\100\33\0\1\101\7\0\1\102\32\0\1\103\35\0"+
    "\1\104\42\0\1\105\15\0\1\106\51\0\1\107\1\0"+
    "\1\10\2\0\5\10\1\110\22\10\2\0\6\10\1\111"+
    "\21\10\2\0\5\10\1\74\22\10\2\0\13\10\1\13"+
    "\13\10\10\0\1\112\32\0\1\113\30\0\1\100\37\0"+
    "\1\114\13\0\1\101\2\0\27\101\7\0\1\115\42\0"+
    "\1\116\33\0\1\105\16\0\1\117\50\0\1\120\33\0"+
    "\1\62\1\0\1\10\2\0\6\10\1\121\21\10\2\0"+
    "\12\10\1\13\14\10\11\0\1\122\35\0\1\123\24\0"+
    "\1\124\32\0\1\125\30\0\1\120\37\0\1\62\13\0"+
    "\1\10\2\0\7\10\1\126\17\10\12\0\1\127\30\0"+
    "\1\130\35\0\1\62\14\0\1\10\2\0\10\10\1\131"+
    "\16\10\13\0\1\132\30\0\1\133\17\0\1\10\2\0"+
    "\11\10\1\134\15\10\14\0\1\135\30\0\1\136\16\0"+
    "\1\10\2\0\12\10\1\74\14\10\15\0\1\137\30\0"+
    "\1\140\33\0\1\141\30\0\1\120\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2288];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\2\1\1\11\7\1\1\11\1\1\1\11\16\1"+
    "\2\11\7\1\6\0\1\11\6\0\4\1\4\0\1\1"+
    "\6\0\2\1\2\0\1\11\4\0\1\1\1\0\1\11"+
    "\2\0\1\1\2\0\1\1\2\0\1\1\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Stack<Integer> yystates = new Stack<Integer> () {{ push(YYINITIAL); }};
    public boolean trace = false;

    public void yystatePush(int yystate) {
        if(trace) System.out.println(">>>> PUSH: " + LexicalState.fromLexer(yystate) + " [" + reverseAndMap(yystates) + "]");
        yybegin(yystate);
        yystates.push(yystate);
    }

    private String reverseAndMap(Stack<Integer> yystates) {
        StringBuilder builder = new StringBuilder();
        for(int i=yystates.size()-1; i>=0; i--) {
            if(builder.length()>0)
                builder.append(", ");
            builder.append(LexicalState.fromLexer(yystates.get(i)));
        }
        return builder.toString();
    }

    public void yystatePopNPush(int yystate) {
        yystatePopNPush(1, yystate);
    }

    public void yystatePopNPush(int nb, int yystate) {
        if(trace) System.out.println(">>>> POP'n PUSH : #" + nb + ", " + LexicalState.fromLexer(yystate) + " [" + reverseAndMap(yystates) + "]");
        for (int i = 0; i < nb; i++) {
            yystatePop();
        }
        yystatePush(yystate);
    }

    public int yystatePop() {
        int popped = yystates.pop();
        if(trace) System.out.println(">>>> POP : " + LexicalState.fromLexer(popped) + " [" + reverseAndMap(yystates) + "]");
        if(!yystates.isEmpty()) {
            yybegin(yystates.peek());
        }// otherwise hopes a push will follow right after
        return popped;
    }

    public boolean checkAhead(char c) {
        if (zzMarkedPos >= zzBuffer.length())
            return false;
        return zzBuffer.charAt(zzMarkedPos) == c;
    }


  _StoryLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _StoryLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 92) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { return StoryTokenType.META_KEY;
          }
        case 18: break;
        case 10: 
          { return StoryTokenType.TABLE_CELL;
          }
        case 19: break;
        case 6: 
          { return StoryTokenType.SCENARIO_TEXT;
          }
        case 20: break;
        case 16: 
          { yystatePopNPush(2, IN_META);     return StoryTokenType.META;
          }
        case 21: break;
        case 15: 
          { yystatePopNPush(2, IN_STEP);     return StoryTokenType.STEP_TYPE;
          }
        case 22: break;
        case 13: 
          { yystatePush(IN_DIRECTIVE); yypushback(yytext().length());
          }
        case 23: break;
        case 12: 
          { return StoryTokenType.TABLE_DELIM;
          }
        case 24: break;
        case 5: 
          { yystatePopNPush(1, IN_TABLE);    return StoryTokenType.TABLE_DELIM;
          }
        case 25: break;
        case 4: 
          { return StoryTokenType.WHITE_SPACE;
          }
        case 26: break;
        case 7: 
          { return StoryTokenType.STEP_TEXT;
          }
        case 27: break;
        case 17: 
          { yystatePopNPush(2, IN_SCENARIO); return StoryTokenType.SCENARIO_TYPE;
          }
        case 28: break;
        case 11: 
          { yystatePop(); yypushback(1);
          }
        case 29: break;
        case 8: 
          { return StoryTokenType.META_TEXT;
          }
        case 30: break;
        case 1: 
          { return StoryTokenType.STORY_DESCRIPTION;
          }
        case 31: break;
        case 2: 
          { yystatePush(IN_STORY); yypushback(yytext().length());
          }
        case 32: break;
        case 3: 
          { return StoryTokenType.BAD_CHARACTER;
          }
        case 33: break;
        case 14: 
          { yystatePop();                    return StoryTokenType.COMMENT;
          }
        case 34: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
